import os

FLASK_SECRET_KEY = os.environ.get('FLASK_SECRET_KEY', 'SECRETS_SECRETS_ARE_NO_FUN')
TWITTER_CONSUMER_KEY = os.environ.get('TWITTER_CONSUMER_KEY', '')
TWITTER_CONSUMER_SECRET = os.environ.get('TWITTER_CONSUMER_SECRET', '')